# Generated by Django 4.2.12 on 2024-05-07 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0002_books_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['created']},
        ),
    ]
